add go fmt check

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -15,6 +15,18 @@ jobs:
 
     - name: Check out code into the Go module directory
       uses: actions/checkout@v1
+    
+    - name: Check format
+      run: |
+        files=$(gofmt -l `find . -name '*.go'`)
+        if [[ -n ${files} ]]; then
+          >&2 echo "Go fmt check failed on the following files:"
+          >&2 echo ""
+          >&2 echo "${files}"
+          >&2 echo ""
+          >&2 echo "Please run \`gofmt -w .\` to reformat code."
+          exit 1
+        fi
 
     - name: Build
       run: |
